# --------------------------------------------------------------------------
# Software:     InVesalius - Software de Reconstrucao 3D de Imagens Medicas
# Copyright:    (C) 2001  Centro de Pesquisas Renato Archer
# Homepage:     http://www.softwarepublico.gov.br
# Contact:      invesalius@cti.gov.br
# License:      GNU - GPL 2 (LICENSE.txt/LICENCA.txt)
# --------------------------------------------------------------------------
"""Report tool — Issue #97.

Generates a self-contained HTML case report containing:
  - Basic case / DICOM information (header)
  - Measurements table
  - Screenshot (embedded as base64 PNG)
  - Simple HTML template (satisfies "template possibility")
"""

import base64
import datetime
import os
import tempfile

import wx

import invesalius.constants as const
import invesalius.project as proj
from invesalius.i18n import tr as _
from invesalius.pubsub import pub as Publisher

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_LOCATION_LABEL = {
    const.AXIAL: "Axial",
    const.CORONAL: "Coronal",
    const.SAGITAL: "Sagittal",
    const.SURFACE: "3D Surface",
}

_TYPE_LABEL = {
    const.LINEAR: "Linear",
    const.ANGULAR: "Angular",
    const.CURVED_LINEAR: "Curved Linear",
    const.DENSITY_ELLIPSE: "Density (Ellipse)",
    const.DENSITY_POLYGON: "Density (Polygon)",
}


def _format_value(m):
    """Return a human-readable value string for a measurement."""
    t = m.type
    v = m.value
    if t == const.LINEAR:
        return f"{v:.3f} mm"
    elif t == const.CURVED_LINEAR:
        return f"{v:.3f} mm"
    elif t == const.ANGULAR:
        return f"{v:.3f}°"
    elif t in (const.DENSITY_ELLIPSE, const.DENSITY_POLYGON):
        return f"{v:.3f} HU"
    return str(v)


# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>InVesalius Case Report</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 40px; color: #222; }}
  h1   {{ color: #1a5276; border-bottom: 2px solid #1a5276; padding-bottom: 6px; }}
  h2   {{ color: #1a5276; margin-top: 32px; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 12px; }}
  th   {{ background: #1a5276; color: white; padding: 8px 12px; text-align: left; }}
  td   {{ padding: 7px 12px; border-bottom: 1px solid #ddd; }}
  tr:nth-child(even) td {{ background: #eaf0fb; }}
  .info-table td:first-child {{ font-weight: bold; width: 200px; color: #555; }}
  .screenshots-grid {{ display: flex; flex-wrap: wrap; gap: 16px; margin-top: 12px; }}
  .shot-card {{ text-align: center; }}
  .shot-label {{ font-weight: bold; margin-bottom: 4px; color: #1a5276; }}
  .screenshot {{ max-width: 420px; border: 1px solid #ccc; display: block; }}
  .footer {{ margin-top: 48px; font-size: 11px; color: #888; border-top: 1px solid #ddd; padding-top: 8px; }}
</style>
</head>
<body>

<h1>InVesalius Case Report</h1>

<h2>Case Information</h2>
<table class="info-table">
  <tr><td>{label_name}</td><td>{case_name}</td></tr>
  <tr><td>{label_modality}</td><td>{modality}</td></tr>
  <tr><td>{label_window}</td><td>{window}</td></tr>
  <tr><td>{label_level}</td><td>{level}</td></tr>
  <tr><td>{label_date}</td><td>{report_date}</td></tr>
</table>

<h2>Measurements</h2>
{measurements_html}

<h2>Screenshots</h2>
<div class="screenshots-grid">
{screenshot_html}
</div>

<div class="footer">
  Generated by InVesalius &bull; {report_date}
</div>
</body>
</html>
"""

_NO_MEASURES_HTML = "<p><em>No measurements recorded.</em></p>"

_SCREENSHOT_PLACEHOLDER = "<p><em>No screenshots taken.</em></p>"

# Each captured view gets a labelled figure card
_SCREENSHOT_CARD_HTML = """\
<div class="shot-card">
  <div class="shot-label">{label}</div>
  <img src="data:image/png;base64,{b64}" class="screenshot" alt="{label}">
</div>"""


_MEASURE_TABLE_HTML = """\
<table>
  <tr>
    <th>#</th>
    <th>{label_name}</th>
    <th>{label_type}</th>
    <th>{label_location}</th>
    <th>{label_value}</th>
  </tr>
  {rows}
</table>"""

_MEASURE_ROW_HTML = (
    "<tr>"
    "<td>{index}</td>"
    "<td>{name}</td>"
    "<td>{type}</td>"
    "<td>{location}</td>"
    "<td>{value}</td>"
    "</tr>"
)


# ---------------------------------------------------------------------------
# Dialog
# ---------------------------------------------------------------------------


class ReportDialog(wx.Dialog):
    """Floating report-generation dialog (non-modal).

    Opens from *5. Export data → Open report tool...*.
    """

    def __init__(self, parent=None):
        super().__init__(
            parent,
            title=_("Case Report"),
            style=wx.DEFAULT_DIALOG_STYLE | wx.FRAME_FLOAT_ON_PARENT | wx.RESIZE_BORDER,
        )
        self._screenshots = []  # list of (label, b64) tuples
        self._tmp_screenshots = []  # list of temp file paths

        self._init_gui()
        self._bind_events()
        self._populate_case_info()

        self.SetMinSize(wx.Size(420, 480))
        self.Fit()
        self.CentreOnScreen()

    # ------------------------------------------------------------------
    # GUI
    # ------------------------------------------------------------------

    def _init_gui(self):
        panel = wx.Panel(self)

        # --- Case info (read-only) ---
        info_box = wx.StaticBox(panel, label=_("Case Information"))
        info_sizer = wx.StaticBoxSizer(info_box, wx.VERTICAL)

        grid = wx.FlexGridSizer(rows=0, cols=2, hgap=8, vgap=4)
        grid.AddGrowableCol(1, 1)

        def add_row(label, attr):
            lbl = wx.StaticText(panel, label=label + ":")
            lbl.SetFont(lbl.GetFont().Bold())
            ctrl = wx.TextCtrl(panel, style=wx.TE_READONLY, name=attr)
            setattr(self, attr, ctrl)
            grid.Add(lbl, 0, wx.ALIGN_CENTER_VERTICAL)
            grid.Add(ctrl, 1, wx.EXPAND)

        add_row(_("Patient / Case Name"), "txt_name")
        add_row(_("Modality"), "txt_modality")
        add_row(_("Window"), "txt_window")
        add_row(_("Level"), "txt_level")

        info_sizer.Add(grid, 1, wx.EXPAND | wx.ALL, 6)

        # --- Screenshot ---
        shot_box = wx.StaticBox(panel, label=_("Screenshot"))
        shot_sizer = wx.StaticBoxSizer(shot_box, wx.VERTICAL)

        self.btn_screenshot = wx.Button(panel, label=_("Take Screenshots…"))
        self.lbl_shot_status = wx.StaticText(panel, label=_("No screenshots taken yet."))

        shot_sizer.Add(self.btn_screenshot, 0, wx.ALL, 6)
        shot_sizer.Add(self.lbl_shot_status, 0, wx.LEFT | wx.BOTTOM, 8)

        # --- Measurements (summary label) ---
        meas_box = wx.StaticBox(panel, label=_("Measurements"))
        meas_sizer = wx.StaticBoxSizer(meas_box, wx.VERTICAL)

        self.lbl_measures = wx.StaticText(panel, label="")
        meas_sizer.Add(self.lbl_measures, 0, wx.ALL, 6)
        self._refresh_measure_label()

        # --- Buttons ---
        btn_save = wx.Button(panel, label=_("Save Report…"))
        btn_close = wx.Button(panel, label=_("Close"))

        btn_sizer = wx.BoxSizer(wx.HORIZONTAL)
        btn_sizer.AddStretchSpacer()
        btn_sizer.Add(btn_save, 0, wx.RIGHT, 8)
        btn_sizer.Add(btn_close, 0)

        # --- Main layout ---
        main = wx.BoxSizer(wx.VERTICAL)
        main.Add(info_sizer, 0, wx.EXPAND | wx.ALL, 8)
        main.Add(shot_sizer, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.BOTTOM, 8)
        main.Add(meas_sizer, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.BOTTOM, 8)
        main.Add(btn_sizer, 0, wx.EXPAND | wx.ALL, 8)

        panel.SetSizer(main)

        outer = wx.BoxSizer(wx.VERTICAL)
        outer.Add(panel, 1, wx.EXPAND)
        self.SetSizer(outer)

        self.btn_save = btn_save
        self.btn_close = btn_close

    # ------------------------------------------------------------------
    # Events
    # ------------------------------------------------------------------

    def _bind_events(self):
        self.btn_screenshot.Bind(wx.EVT_BUTTON, self._on_take_screenshot)
        self.btn_save.Bind(wx.EVT_BUTTON, self._on_save)
        self.btn_close.Bind(wx.EVT_BUTTON, lambda _: self.Close())

        Publisher.subscribe(self._on_project_close, "Close project data")

    def _on_project_close(self):
        wx.CallAfter(self.Close)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _populate_case_info(self):
        """Fill the read-only fields from the current project."""
        project = proj.Project()
        self.txt_name.SetValue(str(project.name) if project.name else _("(unknown)"))
        self.txt_modality.SetValue(str(project.modality) if project.modality else _("(unknown)"))
        self.txt_window.SetValue(str(project.window) if project.window else "-")
        self.txt_level.SetValue(str(project.level) if project.level else "-")

    def _refresh_measure_label(self):
        project = proj.Project()
        n = len(project.measurement_dict)
        if n == 0:
            self.lbl_measures.SetLabel(_("No measurements recorded."))
        elif n == 1:
            self.lbl_measures.SetLabel(_("1 measurement will be included in the report."))
        else:
            self.lbl_measures.SetLabel(
                _("{n} measurements will be included in the report.").format(n=n)
            )

    def _on_take_screenshot(self, evt):
        """Let the user pick MULTIPLE views via checkboxes, capture each one."""
        choices = [
            (_("Axial slice"), const.AXIAL),
            (_("Coronal slice"), const.CORONAL),
            (_("Sagittal slice"), const.SAGITAL),
            (_("3D Volume view"), const.VOLUME),
        ]
        labels = [c[0] for c in choices]

        dlg = wx.MultiChoiceDialog(
            self,
            _("Select one or more views to include in the report:"),
            _("Choose Views"),
            labels,
        )
        # Pre-select Axial, Coronal, Sagittal by default
        dlg.SetSelections([0, 1, 2])

        if dlg.ShowModal() != wx.ID_OK:
            dlg.Destroy()
            return

        selected_indices = dlg.GetSelections()
        dlg.Destroy()

        if not selected_indices:
            self.lbl_shot_status.SetLabel(_("No views selected."))
            return

        captured = []
        failed = []

        for idx in selected_indices:
            label, orientation = choices[idx]
            try:
                fd, path = tempfile.mkstemp(suffix=".png")
                os.close(fd)
                self._tmp_screenshots.append(path)

                Publisher.sendMessage(
                    "Export picture to file",
                    orientation=orientation,
                    filename=path,
                    filetype=const.FILETYPE_PNG,
                )

                if os.path.exists(path) and os.path.getsize(path) > 0:
                    with open(path, "rb") as f:
                        b64 = base64.b64encode(f.read()).decode("ascii")
                    self._screenshots.append((label, b64))
                    captured.append(label)
                else:
                    failed.append(label)
            except Exception as e:
                failed.append(f"{label} ({e})")

        parts = []
        if captured:
            parts.append(_("Captured: ") + ", ".join(captured) + " ✓")
        if failed:
            parts.append(_("Failed: ") + ", ".join(failed))
        self.lbl_shot_status.SetLabel("  |  ".join(parts))

    def _build_html(self):
        """Assemble the full HTML report string."""
        project = proj.Project()

        # --- Measurements ---
        d = project.measurement_dict
        if d:
            rows = ""
            for i in sorted(d.keys()):
                m = d[i]
                t_label = _TYPE_LABEL.get(m.type, str(m.type))
                loc_label = _LOCATION_LABEL.get(m.location, str(m.location))
                rows += _MEASURE_ROW_HTML.format(
                    index=i + 1,
                    name=m.name,
                    type=t_label,
                    location=loc_label,
                    value=_format_value(m),
                )
            measurements_html = _MEASURE_TABLE_HTML.format(
                label_name=_("Name"),
                label_type=_("Type"),
                label_location=_("Location"),
                label_value=_("Value"),
                rows=rows,
            )
        else:
            measurements_html = _NO_MEASURES_HTML

        # --- Screenshots ---
        if self._screenshots:
            cards = "".join(
                _SCREENSHOT_CARD_HTML.format(label=label, b64=b64)
                for label, b64 in self._screenshots
            )
            screenshot_html = cards
        else:
            screenshot_html = _SCREENSHOT_PLACEHOLDER

        report_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

        return _HTML_TEMPLATE.format(
            label_name=_("Patient / Case Name"),
            label_modality=_("Modality"),
            label_window=_("Window"),
            label_level=_("Level"),
            label_date=_("Report Date"),
            case_name=project.name or _("(unknown)"),
            modality=project.modality or _("(unknown)"),
            window=project.window or "-",
            level=project.level or "-",
            report_date=report_date,
            measurements_html=measurements_html,
            screenshot_html=screenshot_html,
        )

    def _on_save(self, evt):
        """Let the user choose where to save the HTML report."""
        self._refresh_measure_label()

        project = proj.Project()
        default_name = (project.name or "report").replace(" ", "_") + "_report.html"

        dlg = wx.FileDialog(
            self,
            message=_("Save Report As…"),
            defaultFile=default_name,
            wildcard="HTML (*.html)|*.html",
            style=wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT,
        )

        if dlg.ShowModal() == wx.ID_OK:
            path = dlg.GetPath()
            if not path.lower().endswith(".html"):
                path += ".html"
            try:
                html = self._build_html()
                with open(path, "w", encoding="utf-8") as f:
                    f.write(html)
                wx.MessageBox(
                    _("Report saved to:\n{path}").format(path=path),
                    _("Report Saved"),
                    wx.OK | wx.ICON_INFORMATION,
                )
            except Exception as e:
                wx.MessageBox(
                    _("Failed to save report:\n{e}").format(e=e),
                    _("Error"),
                    wx.OK | wx.ICON_ERROR,
                )
        dlg.Destroy()

    def Destroy(self):
        """Clean up all temp screenshot files on close."""
        try:
            Publisher.unsubscribe(self._on_project_close, "Close project data")
        except Exception:
            pass
        for p in self._tmp_screenshots:
            if p and os.path.exists(p):
                try:
                    os.remove(p)
                except Exception:
                    pass
        return super().Destroy()
