name: CI Checks

on:
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.7

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          prNumber: ${{ github.event.number }}
          output: ' '

      - name: Run pre-commit hooks
        uses: pre-commit/action@v2.0.3
        with: 
          extra_args: --files ${{ steps.file_changes.outputs.files }}

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest 

  combined-checks:
    runs-on: ubuntu-latest
    needs: [pre-commit, run-tests]
    steps:
      - run: echo "All checks passed! Ready to merge."

